### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by karim612** [calvinallen/calvinallen.net#1]
Hello Calvin,

I had a link to your post, about :"Live Unit testing using Visual studio 2017" . 
Now it is leading to a 404  ;(

Can you provide me the new url or may be rediretc old link to the new one.

Thanks !!!

Regards,
Karim

**Comment by calvinallen** [comment]
Hi, @karim612 ,

What link were you previously using?  I am not aware of any changes in the permalink for that post.

The current link (working for me right now) is https://www.calvinallen.net/archive/2017/12/24/live-unit-testing-in-visual-studio-2017/

**Comment by karim612** [comment]
Hello Calvin,


It was shared by a colleague on our facebook@work. And the broken link is
currently
https://www.calvinallen.net/archive/2017/12/23/live-unit-testing-in-visual-studio-2017/
Not sure where it came from.  I just wanted to let you know.

Thanks for the link and your blog  ;)


Karim.




2018-02-10 3:44 GMT+01:00 Calvin A. Allen <notifications@github.com>:

**Comment by calvinallen** [comment]
@karim612 Excellent, thank you, I've added this is an alternate permalink to the post - you're link should be working again :)

Thanks for letting me know, and thanks for reading! :)
